SearchAdapter and RecyclerView
kvinkel/handy-tune pull request #19
Opened 2020-04-16 21:57 UTC by kvinkel

2020-04-22 09:58 UTC, frederiktt reviewed
🐋 Looks Good 🐋

2020-04-25 12:35 UTC, JakobKaae approved these changes

2020-04-27 11:12 UTC, frederiktt requested changes
:neckbeard:

2020-04-27 11:12 UTC, frederiktt approved these changes
:neckbeard:

2020-04-27 13:34 UTC, merged